# Generated by Django 5.2.1 on 2025-05-12 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('gpt_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=400)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='brief.brief')),
            ],
        ),
    ]
