# Generated by Django 5.2.1 on 2025-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0002_brief_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
