# Generated by Django 5.2.1 on 2025-05-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0003_brief_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='paid',
        ),
    ]
