# Generated by Django 5.2.1 on 2025-05-22 20:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0004_remove_brief_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brief',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clinical Brief', 'verbose_name_plural': 'Clinical Briefs'},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['-start_date', 'nct_id'], 'verbose_name': 'Clinical Trial', 'verbose_name_plural': 'Clinical Trials'},
        ),
        migrations.AddField(
            model_name='brief',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', help_text='Current status of the brief generation', max_length=20),
        ),
        migrations.AddField(
            model_name='brief',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the brief was last updated', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created', null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the brief was created', null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='expires_at',
            field=models.DateTimeField(help_text='When the brief expires'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='gpt_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the clinical trial landscape'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the brief', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brief',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this brief', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brief',
            name='topic',
            field=models.CharField(help_text='Medical condition or therapeutic area to analyze', max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='trial',
            name='brief',
            field=models.ForeignKey(help_text='Brief this trial belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='brief.brief'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='nct_id',
            field=models.CharField(help_text='NCT identifier from ClinicalTrials.gov', max_length=20),
        ),
        migrations.AlterField(
            model_name='trial',
            name='phase',
            field=models.CharField(blank=True, help_text='Trial phase (e.g., PHASE1, PHASE2, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sponsor',
            field=models.CharField(blank=True, help_text='Lead sponsor organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start_date',
            field=models.DateField(blank=True, help_text='Trial start date', null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(blank=True, help_text='Current trial status', max_length=50),
        ),
        migrations.AlterField(
            model_name='trial',
            name='title',
            field=models.CharField(help_text='Official trial title', max_length=400),
        ),
        migrations.AlterField(
            model_name='trial',
            name='url',
            field=models.URLField(help_text='Link to ClinicalTrials.gov page'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['owner', '-created_at'], name='brief_brief_owner_i_4273f8_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['status'], name='brief_brief_status_238cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['expires_at'], name='brief_brief_expires_cdf21f_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['brief', '-start_date'], name='brief_trial_brief_i_1d27d8_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['phase'], name='brief_trial_phase_645e17_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['status'], name='brief_trial_status_5a319e_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['sponsor'], name='brief_trial_sponsor_c2cab3_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['nct_id'], name='brief_trial_nct_id_c8adab_idx'),
        ),
    ]
