# Generated by Django 5.2.1 on 2025-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0005_alter_brief_options_alter_trial_options_brief_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='search_metadata',
            field=models.JSONField(blank=True, help_text='Search methodology and transparency data for information specialists', null=True),
        ),
    ]
