# Generated by Django 5.2.1 on 2025-05-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0006_add_search_metadata'),
    ]

    operations = [
    ]
