# Generated by Django 5.2.1 on 2025-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0007_auto_20250523_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='When this brief was last refreshed with new data', null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this brief was first created', null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this brief was last modified', null=True),
        ),
    ]
